spring.application.name=riwitask

# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/riwitask_db
spring.datasource.username=riwitask_user
spring.datasource.password=riwitask_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto de la aplicación
server.port=8080